### ISSUE TITLE
Python erros

### ISSUE THREAD

**Issue by e-Euler** [Eid010n/Python#1]
I am working through this code because I am reading the book as well. All I get is errors when I run it. I compared my code to yours and it is nearly identical so I copy and pasted your code into wing_ide and found that your code gives the same error message as my code.... did this code originally work for you? 
[python problems.docx](https://github.com/WillPennell/Python/files/424055/python.problems.docx)

I have attached a .rtf for you to see the errors. you will need to change the extension because rtf was not supported for github
[python problems.docx](https://github.com/WillPennell/Python/files/424059/python.problems.docx)

**Comment by HIYOMIYO899** [comment]
I tried to use this code some steps works but others doesn't I've tried from the book swell but same errors everytime
what should I do???? if you want to know more about those errors I'll tell once you reply 
thx.

**Comment by gbafana25** [comment]
Looks like there are just some modules that are unimported or undefined

Also, why was there that one time you ran it and it said permission denied? Seems intermittent
